/*
  Generated by otterdog-e2e (resources/org.jsonnet.j2): one self-contained organization configuration.

  Layer 1 (baseline): the LIVE organization profile (plan, billing_email, description, name, email, blog,
  location, company, twitter_username, json-encoded so null stays null; a field missing from the live profile
  is hidden, 'key:: null', so otterdog leaves it unmanaged), the target's baseline settings, baseline custom
  properties, teams and repositories.
  Layer 2 (scenario): fragments of the current scenario step, inserted verbatim. A field hidden by layer 1 or
  by template_overrides stays hidden when a fragment sets it with ':'; use ':::' to manage it again.
  Libraries ('local <name> = (<expression>);', right after the template import) and overlays (object mixins
  applied after layer 2: '<org> + (<overlay>)') are inserted verbatim too.

  Template variables (Jinja2, StrictUndefined; every value below is inserted VERBATIM):
    import_path         vendor path of the template library: 'vendor/<repo_name>/<file>'
    template_overrides  jsonnet object extending the library (e.g. hiding max_cache_size_gb), '' for none
    project, org        otterdog project name and exact-case GitHub login (no quotes or backslashes)
    settings            layer-1 settings fields: 'key: <json>' (scalars) or 'key+: <json>' (objects)
    custom_properties   layer-1 custom property definitions (jsonnet expressions)
    hide_cache_limit    true -> settings.workflows.max_cache_size_gb is hidden (UNSET, never sent)
    teams               layer-1 team expressions (orgs.newTeam(...) { ... })
    repositories        layer-1 repository expressions (orgs.newRepo(...) { ... })
    fragments           layer-2 mapping, keys: settings, teams, secrets, variables, webhooks, rulesets, roles,
                        custom_properties, repositories (lists of expressions; settings: object fields),
                        extra (raw object fields appended to layer 2)
    libraries           optional (name, expression) pairs: one 'local' each, in order (they see orgs and the
                        libraries before them; names are jsonnet identifiers other than orgs, orgs0, std, ...)
    overlays            optional list of object expressions, each one on its own lines: '+ (', overlay, ')'
  Fragments must not end with a line comment: each one is followed by a comma (libraries and overlays may).
*/
local orgs0 = import 'vendor/template/otterdog-defaults.libsonnet';
local orgs = orgs0;

orgs.newOrg('e2e-test-org', 'e2e-test-org') {
  settings+: {
    plan: "free",
    billing_email: "billing@example.org",
    description: "[otterdog-e2e] Dedicated otterdog e2e test organization",
    name: "E2E Test Org",
    email: null,
    blog: "https://example.org",
    location: null,
    company: null,
    twitter_username: null,
  },
  _repositories+: [
    orgs.newRepo("e2e-t3c7z8a5-config") { allow_merge_commit: true, allow_rebase_merge: true, allow_squash_merge: true, delete_branch_on_merge: false, description: "otterdog e2e: organization configuration", private: false, team_permissions: {"e2e-contributors": "push", "otterdog-admins": "admin", "project-leads": "push"} },
    orgs.newRepo("otterdog-e2e-configs") { description: "otterdog e2e: webapp configuration (otterdog.json), org lease and run ledger", private: false },
    orgs.newRepo("otterdog-e2e-defaults") { description: "otterdog e2e: published base templates", private: false },
    orgs.newRepo("otterdog-e2e-fixture-a") { auto_init: true, description: "otterdog e2e: fixture repository", private: false },
  ],
} {
}
