"""The documentation site (mkdocs.yml, docs_hooks.py, docs/requirements.txt, .github/workflows/docs.yml).

* mkdocs.yml: the nav lists every page of docs/ (and the home page the hooks generate from README.md), the hooks are
  loaded, broken links, anchors and pages missing from the nav are warnings (errors with ``mkdocs build --strict``);
* docs/requirements.txt, installed by the docs workflow, is exactly the ``docs`` group of poetry.lock: pinned versions
  and the hashes of every file (``pip install --require-hashes``). After ``poetry lock``, regenerate it:

      .venv/bin/python tests/unit/test_docs_site.py --write
"""

from __future__ import annotations

import re
import sys
import tomllib
from collections.abc import Iterator, Mapping, Sequence
from functools import cache
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
MKDOCS = ROOT / "mkdocs.yml"
LOCK = ROOT / "poetry.lock"
PYPROJECT = ROOT / "pyproject.toml"
REQUIREMENTS = DOCS / "requirements.txt"
GROUP = "docs"
REGENERATE = ".venv/bin/python tests/unit/test_docs_site.py --write"
DIRECT = ("mkdocs", "mkdocs-material", "pymdown-extensions")
SITE_URL = "https://heurtematte.github.io/otterdog-e2e/"
# name==version, an optional environment marker, then the sha256 hashes of its files
PINNED_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*==[0-9][^ ;]*( ; [^-]+)?( --hash=sha256:[0-9a-f]{64})+$")
REPO_URL = "https://github.com/heurtematte/otterdog-e2e"


class _MkDocsLoader(yaml.SafeLoader):
    """SafeLoader reading the ``!!python/...`` tags of mkdocs.yml as plain data (nothing is imported)."""


def _python_tag(loader: yaml.SafeLoader, suffix: str, node: yaml.Node) -> Any:
    """The value under a python tag, as data."""
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node, deep=True)
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node, deep=True)
    assert isinstance(node, yaml.ScalarNode)
    return loader.construct_scalar(node)


_MkDocsLoader.add_multi_constructor("tag:yaml.org,2002:python/", _python_tag)


@cache
def mkdocs_config() -> dict[str, Any]:
    """mkdocs.yml."""
    # _MkDocsLoader is a SafeLoader: the python tags are read as data, nothing is constructed
    data = yaml.load(MKDOCS.read_text(encoding="utf-8"), Loader=_MkDocsLoader)  # noqa: S506
    assert isinstance(data, dict)
    return data


@cache
def lock() -> dict[str, Any]:
    """poetry.lock."""
    return tomllib.loads(LOCK.read_text(encoding="utf-8"))


def nav_pages(nav: Any) -> Iterator[str]:
    """The pages of a nav (a page, a {title: page} or {section: [entries]} mapping, or a list of entries)."""
    if isinstance(nav, str):
        yield nav
    elif isinstance(nav, list):
        for entry in nav:
            yield from nav_pages(entry)
    elif isinstance(nav, dict):
        for value in nav.values():
            yield from nav_pages(value)


def render_requirements(data: Mapping[str, Any]) -> str:
    """docs/requirements.txt: every package of the docs group of the lock, pinned, with the hashes of its files."""
    lines = [
        "# The packages of the documentation site: the docs group of poetry.lock, pinned with the hashes of every file.",
        f"# Generated by tests/unit/test_docs_site.py, do not edit: after `poetry lock`, run {REGENERATE}",
        "# Installed by .github/workflows/docs.yml with pip install --require-hashes --only-binary=:all:",
    ]
    packages = sorted((p for p in data["package"] if GROUP in p.get("groups", [])), key=lambda p: p["name"])
    for package in packages:
        markers = package.get("markers")
        marker = markers.get(GROUP) if isinstance(markers, dict) else markers
        requirement = f"{package['name']}=={package['version']}" + (f" ; {marker}" if marker else "")
        hashes = [f"--hash={entry['hash']}" for entry in sorted(package["files"], key=lambda entry: entry["hash"])]
        lines.append(" \\\n    ".join([requirement, *hashes]))
    return "\n".join(lines) + "\n"


# --- mkdocs.yml --------------------------------------------------------------------------------------------------------
def test_nav_lists_every_page() -> None:
    """Every docs/*.md page is in the nav exactly once, with the home page (index.md, generated from README.md)."""
    pages = list(nav_pages(mkdocs_config()["nav"]))
    assert len(pages) == len(set(pages)), "a page is listed twice"
    assert set(pages) == {path.name for path in DOCS.glob("*.md")} | {"index.md"}
    assert not (DOCS / "index.md").exists(), "the home page is generated from README.md by docs_hooks.py"


def test_site_settings() -> None:
    """Site and repository URLs, the hooks, the edit links on main and strict link and anchor validation."""
    config = mkdocs_config()
    assert config["site_url"] == SITE_URL
    assert config["repo_url"] == REPO_URL
    assert config["edit_uri"] == "edit/main/docs/"
    assert config["hooks"] == ["docs_hooks.py"]
    assert config["validation"] == dict.fromkeys(
        ("omitted_files", "absolute_links", "unrecognized_links", "anchors"), "warn"
    ), "with --strict, broken links and anchors and pages missing from the nav must fail the build"
    assert "README.md" in config["watch"]
    assert config["theme"]["name"] == "material"


def test_markdown_extensions() -> None:
    """GitHub-compatible anchors, mermaid fences, no attr_list (it drops a trailing '{...}' of table cells)."""
    extensions: dict[str, Any] = {}
    for entry in mkdocs_config()["markdown_extensions"]:
        extensions.update(entry if isinstance(entry, dict) else {entry: None})
    assert extensions["toc"]["permalink"] is True
    assert extensions["toc"]["slugify"] == {"kwds": {"case": "lower"}}
    assert extensions["pymdownx.superfences"]["custom_fences"] == [
        {"name": "mermaid", "class": "mermaid", "format": ""}
    ]
    assert "attr_list" not in extensions
    assert {"tables", "admonition", "pymdownx.magiclink", "pymdownx.tilde", "pymdownx.tasklist"} <= set(extensions)


# --- dependencies ------------------------------------------------------------------------------------------------------
def test_docs_group_is_optional() -> None:
    """The docs group of pyproject.toml is optional (`poetry install --with docs`) and holds the site's packages."""
    group = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["tool"]["poetry"]["group"][GROUP]
    assert group["optional"] is True
    assert set(group["dependencies"]) == set(DIRECT)


def test_requirements_match_the_lock() -> None:
    """docs/requirements.txt is the docs group of poetry.lock (versions and hashes)."""
    expected = render_requirements(lock())
    assert REQUIREMENTS.read_text(encoding="utf-8") == expected, f"docs/requirements.txt is stale: run {REGENERATE}"
    pinned = {line.split("==")[0] for line in expected.splitlines() if "==" in line}
    assert set(DIRECT) <= pinned


def test_requirements_pin_every_package_with_hashes() -> None:
    """Every requirement is an exact pin followed by sha256 hashes (pip refuses unhashed ones with --require-hashes)."""
    text = re.sub(r" \\\n\s+", " ", REQUIREMENTS.read_text(encoding="utf-8"))  # join the continuation lines
    requirements = [line for line in text.splitlines() if line and not line.startswith("#")]
    assert len(requirements) >= len(DIRECT)
    for requirement in requirements:
        assert PINNED_RE.match(requirement), requirement


def main(argv: Sequence[str]) -> int:
    """``--write`` regenerates docs/requirements.txt from poetry.lock."""
    if list(argv) != ["--write"]:
        sys.stderr.write(f"usage: {REGENERATE}\n")
        return 2
    REQUIREMENTS.write_text(render_requirements(lock()), encoding="utf-8")
    sys.stdout.write(f"wrote {REQUIREMENTS.relative_to(ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
